### PR TITLE
[4.1] Added baller pagination

### PR DESCRIPTION
**Pull request by SammyK**
I had to refactor the request/response logic slightly to get this to work. But pagination is super-smart now.

When you hit the `/me/photos` endpoint, you might get a response like this:

``` json
{
  "data": [
  ], 
  "paging": {
    "cursors": {
      "before": "TRvek9UUXdPRGdsfsdEYzRNelk9", 
      "after": "TVRTlRvek9UUXsdfdsfBMk5EYzRNelk9"
    }, 
    "next": "https://graph.facebook.com/v2.2/1234/photos?pretty=0&after=TVRTlRvek9UUXsdfdsfBMk5EYzRNelk9"
  }
}
```

It's easy to just grab the `$.paging.next` value, slap on the access token and app secret proof and you've got the next page results. And with the help of `Facebook\Facebook`, you can paginate like so:

``` php
$listOfPhotos = $response->getGraphList();

// Get the next page of results
$nextPageOfPhotos = $fb->next($listOfPhotos);
// Or the previous page of results
$previousPageOfPhotos = $fb->previous($listOfPhotos);
```

But what about then you get deeply-embedded pagination data with just the cursors and no URL?

``` json
{
  "data": [
    {
      "source": "https://scontent-a.xx.fbcdn.net/foo.jpg", 
      "likes": {
        "data": [
          . . .
        ], 
        "paging": {
          "cursors": {
            "before": "NTcwODIzNDE2Mzc3OTU0", 
            "after": "MTAxNTI0NDAwODEzNjU1MjI="
          }
        }
      }, 
    },
    . . .
  ]
}
```

How do you paginate over the likes? `GraphList` to the rescue! You do it just like you would on the root list:

``` php
$listOfPhotos = $response->getGraphList();

// Get the next page of likes for first photo
$nextPageOfLikes = $fb->next($listOfPhotos[0]['likes']);
```

Full example:

``` php
$listOfPages = $response->getGraphList();
// Only grab 5 pages
$maxPages = 5;
$pageCount = 0;

do {
  echo '<h1>Page #' . $page_count . ':</h1>' . "\n\n";

  foreach ($listOfPages as $page) {
    var_dump($page->asArray());

    $likes = $page['likes'];
    do {
      echo '<p>Likes:</p>' . "\n\n";
      var_dump($likes->asArray());
    } while ($likes = $fb->next($likes));
  }
  $pageCount++;
} while ($pageCount < $maxPages && $listOfPages = $fb->next($listOfPages));
```

I added [some documentation](https://github.com/SammyK/facebook-php-sdk-v4/blob/add-pagination/docs/GraphList.fbmd) but it could be expanded on.

I've got another PR ready after this one that adds native [file upload functionality](https://github.com/SammyK/facebook-php-sdk-v4/tree/native-file-upload-support) to both regular and batch requests. Turns out, file uploads have been broken this whole time. Lol. :)

### CODE REVIEW

**Comment by hassankhan** [comment]
@SammyK you are freakin' awesome!

**Comment by SammyK** [comment]
@hassankhan Aw, thanks! :)

**Comment by hassankhan** [comment]
Sorry for the off-topic, but is there a release timeline for 4.1?

**Comment by gfosco** [comment]
It will be tagged 5.0, hopefully in the next 2-3 weeks.

**Pull request merged**
